from math import pi

integerpart=3
fractionalpart=pi-3
print(integerpart,".")
#1
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#2
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#3
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#4
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#5
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#6
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#7
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#8
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#9
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#10
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#11
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#12
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#13
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#14
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#15
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)
#16
integerpart=int(fractionalpart*8)
fractionalpart=fractionalpart*8-integerpart
print(integerpart)

